# Generated by Django 4.2.4 on 2023-10-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="due_date",
            field=models.DateTimeField(
                blank=True, help_text="DateTime to Complete Task before", null=True
            ),
        ),
    ]
